### ISSUE TITLE
[Cocos Creator] Websocket params problem

### ISSUE THREAD

**Issue by GAMEKON** [gamestdio/websocket#3]
Hi, I'm using Cocos Creator which in "Native Form", the websocket.close() needs no parameters otherwise an error will be thrown. How can I call websocket.close() with no params?

**Comment by endel** [comment]
Hi @GAMEKON, thanks for reporting this. I didn't know about that. Could you provide the error you receive from Cocos Creator? Cheers!

**Comment by GAMEKON** [comment]
nono, never mind, it's cocos's problem, you did well.
